### ISSUE TITLE
"Error loading replay..."

### ISSUE THREAD

**Issue by XaICyRiC** [HearthSim/Joust#218]
Hi there,

I recently found myself unable to watch any of my replays, receiving the "error loading replay..." message each time. I was previously able to watch them without any issues, and I haven't changed anything on my system recently. I tried Googling the issue and found one person who fixed it by disabling their ad blocker, but doing so didn't fix the problem for me.

I would greatly appreciate any help on this issue.

Thanks!

**Comment by jleclanche** [comment]
What's your browser?

Disabling adblocker is indeed a common solution. What you can also try is disabling any other extension you have that might block network requests, or trying a different browser.

I'm closing this ticket because this issue tracker is for bugs with the replayer; but feel free to keep replying here. For support you can use contact@hsreplay.net or https://discord.gg/hearthsim.
