### ISSUE TITLE
Documentation needed

### ISSUE THREAD

**Issue by tkiraly** [HearthSim/joust#67]
hi,

i'm not an expert on node.js. I tried to install Joust on Heroku for some time but i wasn't successful.
Can you experts, write a more detailed usage guide?

**Comment by beheh** [comment]
Yeah, it's pretty rudimentary now. Where are you stuck? I'm not entirely sure how detailed it should be/which steps are self-explanatory.

**Comment by tkiraly** [comment]
i have a free account on heroku. i forked this repo and uploaded with heroku's integration.

it builds automatically and says build is successful.

I used heroku toolbelt and after logging in i ran the following command:

`heroku run --app mysterious-dusk-30228 npm install -g electron-prebuilt typings gulp webpack`

the result is a tree of dependencies and two warning:

> npm WARN optional Skipping failed optional dependency /webpack/chokidar/fsevents:
> npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.9

then i run:

`heroku run --app mysterious-dusk-30228 npm start`

i get this:

> Running npm start on mysterious-dusk-30228.... up, run.7944
> 
> > Joust@0.0.1 start /app
> > main.js
> 
> sh: 1: main.js: not found
> 
> npm ERR! Linux 3.13.0-79-generic
> npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
> npm ERR! node v5.9.1
> npm ERR! npm  v3.7.3
> npm ERR! file sh
> npm ERR! code ELIFECYCLE
> npm ERR! errno ENOENT
> npm ERR! syscall spawn
> npm ERR! Joust@0.0.1 start: `main.js`
> npm ERR! spawn ENOENT
> npm ERR!
> npm ERR! Failed at the Joust@0.0.1 start script 'main.js'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the Joust package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     main.js
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs Joust
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls Joust
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /app/npm-debug.log

i hope i explained well enough, i'm not into node.js. Can you explain how can i fix this error?

**Comment by beheh** [comment]
Okay, thanks for posting your inputs and the log. There's some misunderstanding here:
Joust is not a node/npm application, it's just plain old Javascript. That means that once you have the `bundle.js` it can be fully run in any browser - your server doesn't need to do anything besides host the Javascript like a normal website.

What we use npm for is managing the dependencies (for example Immutable.js) and the compile toolchain (webpack, TypeScript). You don't need Heroku to run Joust, you can just compile it on any machine and then distribute it to your servers as a normal JS-file. In fact, we might start offering `official` bundles to download and include at some point, and I can look into that at some point (I'd like to close #68 first though.

So in order to get Joust going, just run the commands from the README either on your local machine or any build server, and upload the `dist` directory to your webserver. Feel free to respond if you have any other questions.

**Comment by tkiraly** [comment]
thank you for your explanation!
It works now!
